{% set version = "1.1.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multiroc
  version: {{ version|replace("-", "_") }}

source:
  fn: multiROC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/multiROC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/multiROC/multiROC_{{ version }}.tar.gz
  sha256: a3690e821757a2a6390b7c24e903ebbf999b20df7284d84a617afb366f5fcd97

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-boot
    - r-ggplot2
    - r-magrittr

  run:
    - r-base
    - r-boot
    - r-ggplot2
    - r-magrittr

test:
  commands:
    - $R -e "library('multiROC')"  # [not win]
    - "\"%R%\" -e \"library('multiROC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multiROC
  license: GPL-3
  summary: Tools to solve real-world problems with multiple classes by computing the areas under
    ROC curve via micro-averaging and macro-averaging. The methodology is described
    in V. Van Asch (2013) <https://www.clips.uantwerpen.be/~vincent/pdf/microaverage.pdf> and
    Pedregosa et al. (2011) <http://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
