# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M1vcRmCUL3jIFXvwMrOs3wy6DcLIY4yHaAZjmY0V+Hdznl1oDNs2IEkZ1Ofq478RtphiQjgPSHQebVImESJxOr6nhprUDoB7MXMhs+IPBjdYCUp1xPr9VJZi9uK6vFI2iBRpNFcgGbYRpwM+iRtc4eEnAunDY92limdzEUpY4EBjNy91iM8TFuAdqJb8ADIuzwk+2PcAvA8RzKLXX0WvTnKHs54BIFFxK79gFvuyaZWBNTsOnD12UngadDhHMXCQNbUnONuEoxvXDjxNIXMBMjQ1oCrjQwei6+Vps/JtVvU5Gb6i1V+e+YJfkstv1bJxaJ5GNTnoq60oLvL8PPHzUUrHU+GkidBVkzB8/NqBYSOxWWF7+vQf5EX8wsEqq8XfjCoPUhMlvWufNSDX6+q0fuuhJNic+b2Gyp4dDBaVGWJBTr39rSGsw+an2r7t/wY9Ec0bAyAiE3XjYcd9R53BpPEc+DhecHirVoVdDLZDjfqyZto6pSD/jDrtmQ3wSAzQTMNynB9G5JVhDswlWkuTPz63sZiV7xu+GQy1O9m6UteA/re713JwmCXhAPRse9cyYCSUr9+D6CbtugBbWl7SH8jXqLv177Q+TmZ+/eR/vocOVCjYuSW/x8MujhTDkqc4WCVQ4YztJIwjmqf7kCs3MYjOUdHavgriSwkOoV3iwzQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
