appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: M1vcRmCUL3jIFXvwMrOs3wy6DcLIY4yHaAZjmY0V+Hdznl1oDNs2IEkZ1Ofq478RtphiQjgPSHQebVImESJxOr6nhprUDoB7MXMhs+IPBjdYCUp1xPr9VJZi9uK6vFI2iBRpNFcgGbYRpwM+iRtc4eEnAunDY92limdzEUpY4EBjNy91iM8TFuAdqJb8ADIuzwk+2PcAvA8RzKLXX0WvTnKHs54BIFFxK79gFvuyaZWBNTsOnD12UngadDhHMXCQNbUnONuEoxvXDjxNIXMBMjQ1oCrjQwei6+Vps/JtVvU5Gb6i1V+e+YJfkstv1bJxaJ5GNTnoq60oLvL8PPHzUUrHU+GkidBVkzB8/NqBYSOxWWF7+vQf5EX8wsEqq8XfjCoPUhMlvWufNSDX6+q0fuuhJNic+b2Gyp4dDBaVGWJBTr39rSGsw+an2r7t/wY9Ec0bAyAiE3XjYcd9R53BpPEc+DhecHirVoVdDLZDjfqyZto6pSD/jDrtmQ3wSAzQTMNynB9G5JVhDswlWkuTPz63sZiV7xu+GQy1O9m6UteA/re713JwmCXhAPRse9cyYCSUr9+D6CbtugBbWl7SH8jXqLv177Q+TmZ+/eR/vocOVCjYuSW/x8MujhTDkqc4WCVQ4YztJIwjmqf7kCs3MYjOUdHavgriSwkOoV3iwzQ=}
bot:
  automerge: true
