travis:
  secure:
    BINSTAR_TOKEN: N8Kmz8lXEFq9Zs0o/XJGj8RESAsDA8+bTqUom7f1ew3J/bjLhKN2vcBrCilxvOYXJDBRn7M0kGk35vpLufgEbniWhAGy5fL9dVbAzeNca/HsI7Kl41WdyJj/ILN1ppTBkGfQdnkuc0KrUD7h6ihwasPQMQCOk6GdLmbWIBPxxZEPnhNo5squUBHrwV7PtVqt7Xy+rAziY4ueDXm/LeYtm1aO8ggK0SRNL8EAxkTsmw9kgVrWd98SDd3mkkxUNcCKe8PCSHMOVCF4I2Jv5eX7r3JP5ZGk0x06DgfwnTY3IAJ2SE+hddlpTGjJqK2QOPGrEFO6SFwNNPfuQobGbIE76nDgwyUPm7FGSwgliWQ2s/qc49Zg+Aaq1st0RQW8pSlFwH7kFo9zrRf5UGRMiynPIm2oDvtX5oQje3bag7aeSp6ns9nl9j6Y1xq71yCv7bIw6U815Th13VZ2EaTKLVQaE4X3CxzrgmsgNs58DJJTZQbjHeBox5LAilnf2bvRFJTdDxPAnFAt0JcoqTyfg6U6WP7QiXy+1ltFi1/tQn9HMNhwqFLOscr089YWwE0lZdGurow3idTagqhggU4wQy8sIPSXRIp0uK6fYErQ767JHBFYol5BNMKdOucQ17bB7d5q1Y2fiOVE337yeUoUdZVPRXB5/pLeblKrRNjkUpxkn0w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
